version: '3'

services:
  driver-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=ushi
      - POSTGRES_USER=ushi_usr
      - POSTGRES_PASSWORD=wsWdND5fiuIn1qYx
      - POSTGRES_HOST=45.82.71.122
      - POSTGRES_PORT=5432
    restart: always
